set_property PACKAGE_PIN D3  	[get_ports rst] 			
set_property PACKAGE_PIN D4  	[get_ports clk] 			
set_property PACKAGE_PIN H13	[get_ports key1] 			
set_property PACKAGE_PIN H14	[get_ports key0] 		
set_property PACKAGE_PIN B16	[get_ports buzz] 	
			    		
set_property PACKAGE_PIN J15	[get_ports {enc[0]}]	
set_property PACKAGE_PIN H12	[get_ports {enc[1]}] 		
set_property PACKAGE_PIN J16	[get_ports {enc[2]}]  	
set_property PACKAGE_PIN F12	[get_ports {enc[3]}] 		
	
set_property PACKAGE_PIN A14 	[get_ports {seg_d[0]}]
set_property PACKAGE_PIN B14 	[get_ports {seg_d[1]}]
set_property PACKAGE_PIN A15 	[get_ports {seg_d[2]}]
set_property PACKAGE_PIN B15 	[get_ports {seg_d[3]}]
set_property PACKAGE_PIN B11 	[get_ports {seg_d[4]}]
set_property PACKAGE_PIN A12 	[get_ports {seg_d[5]}]
set_property PACKAGE_PIN B12 	[get_ports {seg_d[6]}]
set_property PACKAGE_PIN A13 	[get_ports {seg_d[7]}]

set_property PACKAGE_PIN B10 	[get_ports {seg_com[0]}]
set_property PACKAGE_PIN A10 	[get_ports {seg_com[1]}]
set_property PACKAGE_PIN B9  	[get_ports {seg_com[2]}]
set_property PACKAGE_PIN A9  	[get_ports {seg_com[3]}]
set_property PACKAGE_PIN G11 	[get_ports {seg_com[4]}]
set_property PACKAGE_PIN H11 	[get_ports {seg_com[5]}]
set_property PACKAGE_PIN C8  	[get_ports {seg_com[6]}]
set_property PACKAGE_PIN D8  	[get_ports {seg_com[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports rst] 			
set_property IOSTANDARD LVCMOS33 [get_ports clk] 			
set_property IOSTANDARD LVCMOS33 [get_ports key0] 			
set_property IOSTANDARD LVCMOS33 [get_ports key1] 		
set_property IOSTANDARD LVCMOS33 [get_ports buzz] 	

set_property IOSTANDARD LVCMOS33 [get_ports {enc[0]}] 		
set_property IOSTANDARD LVCMOS33 [get_ports {enc[1]}] 		
set_property IOSTANDARD LVCMOS33 [get_ports {enc[2]}] 		
set_property IOSTANDARD LVCMOS33 [get_ports {enc[3]}] 	
	
set_property IOSTANDARD LVCMOS33 [get_ports {seg_d[0]}] 	
set_property IOSTANDARD LVCMOS33 [get_ports {seg_d[1]}] 	
set_property IOSTANDARD LVCMOS33 [get_ports {seg_d[2]}] 	
set_property IOSTANDARD LVCMOS33 [get_ports {seg_d[3]}] 	
set_property IOSTANDARD LVCMOS33 [get_ports {seg_d[4]}] 	
set_property IOSTANDARD LVCMOS33 [get_ports {seg_d[5]}] 	
set_property IOSTANDARD LVCMOS33 [get_ports {seg_d[6]}] 	
set_property IOSTANDARD LVCMOS33 [get_ports {seg_d[7]}] 	

set_property IOSTANDARD LVCMOS33 [get_ports {seg_com[0]}] 	
set_property IOSTANDARD LVCMOS33 [get_ports {seg_com[1]}] 	
set_property IOSTANDARD LVCMOS33 [get_ports {seg_com[2]}] 	
set_property IOSTANDARD LVCMOS33 [get_ports {seg_com[3]}] 	
set_property IOSTANDARD LVCMOS33 [get_ports {seg_com[4]}] 	
set_property IOSTANDARD LVCMOS33 [get_ports {seg_com[5]}] 	
set_property IOSTANDARD LVCMOS33 [get_ports {seg_com[6]}] 	
set_property IOSTANDARD LVCMOS33 [get_ports {seg_com[7]}] 	
